# frozen_string_literal: true

####### THIS FILE IS AUTOMATICALLY GENERATED BY protoc-gen-rails. DO NOT MODIFY. #######


get '/test/*foobar' => 'my_service#test' 
post '/test2' => 'my_service#test2' 
post '/test3/*sub_id' => 'my_service#test3' 
post '/test4' => 'my_service#test4' 

