# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test_service.proto for package 'testdata'

require 'grpc'
require 'test_service_pb'

module Testdata
  module MyService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'testdata.MyService'

      rpc :Test, ::Testdata::TestRequest, ::Testdata::TestResponse
      rpc :Test2, ::Testdata::TestRequest, ::Testdata::TestResponse
      rpc :Test3, ::Testdata::TestRequest, ::Testdata::TestResponse
      rpc :Test4, ::Testdata::TestRequest, ::Testdata::TestResponse
    end

    Stub = Service.rpc_stub_class
  end
end
