
####### THIS FILE IS AUTOMATICALLY GENERATED BY protoc-gen-rails. DO NOT MODIFY. #######

get "/test/:blah/:repeated_string" => "my_service#test"
post "/test2" => "my_service#test_2"
post "/test3/:sub_id" => "my_service#test_3"
